# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "sql_exporter"
    static_configs:
      - targets: ["localhost:9399"]  # Replace with SQL Exporter host

  - job_name: 'gitlab_commit_exporter'
    static_configs:
      - targets: ['localhost:9101']

  - job_name: 'gitlab_group_commit_exporter'  # Monitoring commits for all projects in a group
    static_configs:
      - targets: ['localhost:9102']  # Ensure the script listens on port 9102

  - job_name: 'gitlab_metrics'
    static_configs:
      - targets: ['localhost:9025']
